### ISSUE TITLE
SQL: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by ncovercash** [rx-ts/prettier#144]
It seems the SQL parser is choking on some table definitions I have for Postgres:

```sql
CREATE TABLE "test" (
    "id" uuid NOT NULL
) WITH (oids = false);
```

It is entirely dependent on this `WITH` clause -- without it, the plugin works as expected.

Here's a traceback:
```
[error] src\test\resources\database-migrate-setup.sql: TypeError: Cannot read property 'slice' of undefined
[error]     at parseKey (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:2460:20)
[error]     at Tokenizer.getPlaceholderTokenWithKey (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:2504:21)
[error]     at Tokenizer.getIdentNamedPlaceholderToken (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:2456:19)
[error]     at Tokenizer.getPlaceholderToken (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:2451:19)
[error]     at Tokenizer.getNextToken (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:2396:147)
[error]     at Tokenizer.tokenize (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:2376:24)
[error]     at StandardSqlFormatter.format (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:1958:38)
[error]     at format (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:3541:29)
[error]     at Object.print (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier-plugin-sql\lib\cjs.js:3708:44)
[error]     at callPluginPrintFunction (C:\Users\ncovercash\AppData\Roaming\npm\node_modules\prettier\index.js:13787:21)
```

And my prettier config:
```
{
  "printWidth": 100,
  "useTabs": false,
  "tabWidth": 2,
  "semi": true,
  "proseWrap": "always",
  "trailingComma": "all",
  "quoteProps": "consistent",
  "bracketSameLine": false,
  "xmlWhitespaceSensitivity": "ignore"
}
```

**Comment by jefbarn** [comment]
Had the same until I added this to my prettier config
---
    "formatter": "sql-formatter",
    "language": "postgresql"
---

**Comment by JounQin** [comment]
Please provide a runnable reproduction.

**Comment by ncovercash** [comment]
@JounQin the three lines at the top of the first post causes the issue.

@jefbarn where is this added?  I'd imagine not to the root of the prettier config but I am not sure of where formatter-specific settings go.

**Comment by JounQin** [comment]
@ncovercash The default language option is `sql`, if you're using `postgresql` you need to override it specifically.

See also https://github.com/rx-ts/prettier/tree/master/packages/sql#parser-options

And https://prettier.io/docs/en/configuration.html#configuration-overrides
